/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Analytics: typeof import('./src/components/chat/Analytics.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    CodeSnippets: typeof import('./src/components/chat/CodeSnippets.vue')['default']
    ConversationList: typeof import('./src/components/chat/ConversationList.vue')['default']
    ErrorBoundary: typeof import('./src/components/common/ErrorBoundary.vue')['default']
    ExportDialog: typeof import('./src/components/chat/ExportDialog.vue')['default']
    GestureHandler: typeof import('./src/components/common/GestureHandler.vue')['default']
    LoadingMessage: typeof import('./src/components/chat/LoadingMessage.vue')['default']
    MessageEditor: typeof import('./src/components/chat/MessageEditor.vue')['default']
    MessagePreview: typeof import('./src/components/chat/MessagePreview.vue')['default']
    MessageQuote: typeof import('./src/components/chat/MessageQuote.vue')['default']
    MessageSearch: typeof import('./src/components/chat/MessageSearch.vue')['default']
    MessageSkeleton: typeof import('./src/components/chat/MessageSkeleton.vue')['default']
    PromptTemplates: typeof import('./src/components/chat/PromptTemplates.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareDialog: typeof import('./src/components/chat/ShareDialog.vue')['default']
    ThemeSwitch: typeof import('./src/components/common/ThemeSwitch.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanDropdownItem: typeof import('vant/es')['DropdownItem']
    VanDropdownMenu: typeof import('vant/es')['DropdownMenu']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanTag: typeof import('vant/es')['Tag']
    VirtualList: typeof import('./src/components/common/VirtualList.vue')['default']
    VoiceInput: typeof import('./src/components/chat/VoiceInput.vue')['default']
  }
}
