"""Change priority field to string in notes table

Revision ID: 39251e0dfc04
Revises: 5fa602ac146c
Create Date: 2024-12-02 21:30:26.567523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '39251e0dfc04'
down_revision: Union[str, None] = '5fa602ac146c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'priority',
                   existing_type=sa.Integer(),
                   type_=sa.String(length=50),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'priority',
                   existing_type=sa.String(length=50),
                   type_=sa.Integer(),
                   existing_nullable=False)
    # ### end Alembic commands ###
