"""v1.2.0 添加 知识手册的接口

Revision ID: 7a7e60a4366b
Revises: 55d97d53cc79
Create Date: 2024-11-28 18:42:07.942522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7e60a4366b'
down_revision: Union[str, None] = '55d97d53cc79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
