"""initial

Revision ID: 7aa405a46ea9
Revises: 
Create Date: 2024-11-25 14:04:22.324477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7aa405a46ea9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('name', sa.String(length=100), nullable=True))
    op.alter_column('messages', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_constraint('messages_ibfk_1', 'messages', type_='foreignkey')
    op.drop_constraint('messages_ibfk_2', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['parent_message_id'], ['id'])
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_ibfk_2', 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('messages_ibfk_1', 'messages', 'messages', ['parent_message_id'], ['id'], ondelete='SET NULL')
    op.alter_column('messages', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('messages', 'role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('conversations', 'name')
    # ### end Alembic commands ###
