"""add name to conversation

Revision ID: bda210cf54ce
Revises: 7aa405a46ea9
Create Date: 2024-11-25 14:04:42.764667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda210cf54ce'
down_revision: Union[str, None] = '7aa405a46ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_message_parent', 'messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_message_parent', 'messages', 'messages', ['parent_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
